<a href="https://colab.research.google.com/github/kunal919109/DSBDA/blob/main/Copy_of_Pract2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:

import numpy as np

In [ ]:
data = {
    'ID':[1,2,3,4,5],
    'Name':['Kunal', 'Tejas', 'Rahul', 'Sujal', 'Amol'],
    'Math':[85, 90, np.nan, 66, 125],
    'Science':[78, 88, 92, None, 65],
    'English':[80, 85, 70, 60, 75],
    'Attendance':[0.92, 0.85, 0.95, 0.40, 1.10]
}

In [ ]:

print(data)

{'ID': [1, 2, 3, 4, 5], 'Name': ['Kunal', 'Tejas', 'Rahul', 'Sujal', 'Amol'], 'Math': [77, 90, nan, 66, 134], 'Science': [78, 88, 92, None, 65], 'English': [80, 85, 70, 60, 75], 'Attendance': [0.92, 0.85, 0.95, 0.4, 1.1]}

In [ ]:

df = pd.DataFrame(data)

In [ ]:
print(df)

   ID   Name   Math  Science  English  Attendance
0   1  Kunal   77.0     78.0       80        0.92
1   2  Tejas   90.0     88.0       85        0.85
2   3  Rahul    NaN     92.0       70        0.95
3   4  Sujal   66.0      NaN       60        0.40
4   5   Amol  134.0     65.0       75        1.10

In [ ]:
df.isnull().sum()

ID            0
Name          0
Math          1
Science       1
English       0
Attendance    0
dtype: int64

In [ ]:

df.dtypes

ID              int64
Name           object
Math          float64
Science       float64
English         int64
Attendance    float64
dtype: object

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

             ID        Math    Science    English  Attendance
count  5.000000    4.000000   4.000000   5.000000    5.000000
mean   3.000000   91.750000  80.750000  74.000000    0.844000
std    1.581139   29.825884  12.038134   9.617692    0.264443
min    1.000000   66.000000  65.000000  60.000000    0.400000
25%    2.000000   74.250000  74.750000  70.000000    0.850000
50%    3.000000   83.500000  83.000000  75.000000    0.920000
75%    4.000000  101.000000  89.000000  80.000000    0.950000
max    5.000000  134.000000  92.000000  85.000000    1.100000

In [ ]:
df.loc[len(df)] = df.loc[1]

In [ ]:
df

   ID   Name   Math  Science  English  Attendance
0   1  Kunal   77.0     78.0       80        0.92
1   2  Tejas   90.0     88.0       85        0.85
2   3  Rahul    NaN     92.0       70        0.95
3   4  Sujal   66.0      NaN       60        0.40
4   5   Amol  134.0     65.0       75        1.10
5   2  Tejas   90.0     88.0       85        0.85

In [ ]:

df[df.duplicated(subset=['Math'])]

   ID   Name  Math  Science  English  Attendance
5   2  Tejas  90.0     88.0       85        0.85

In [ ]:

df = df.drop_duplicates()

In [ ]:

df

   ID   Name   Math  Science  English  Attendance
0   1  Kunal   77.0     78.0       80        0.92
1   2  Tejas   90.0     88.0       85        0.85
2   3  Rahul    NaN     92.0       70        0.95
3   4  Sujal   66.0      NaN       60        0.40
4   5   Amol  134.0     65.0       75        1.10

In [ ]:
df['Math'] = df['Math'].fillna(df['Math'].mean())

/tmp/ipykernel_4826/1038178227.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Math'] = df['Math'].fillna(df['Math'].mean())

In [ ]:
df

   ID   Name    Math  Science  English  Attendance
0   1  Kunal   77.00     78.0       80        0.92
1   2  Tejas   90.00     88.0       85        0.85
2   3  Rahul   91.75     92.0       70        0.95
3   4  Sujal   66.00      NaN       60        0.40
4   5   Amol  134.00     65.0       75        1.10

In [ ]:
df['Science'] = df['Science'].fillna(df['Science'].median())

/tmp/ipykernel_4826/368293247.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Science'] = df['Science'].fillna(df['Science'].median())

In [ ]:

df

   ID   Name    Math  Science  English  Attendance
0   1  Kunal   77.00     78.0       80        0.92
1   2  Tejas   90.00     88.0       85        0.85
2   3  Rahul   91.75     92.0       70        0.95
3   4  Sujal   66.00     83.0       60        0.40
4   5   Amol  134.00     65.0       75        1.10

In [ ]:
def attend(x):
    return min(x, 1)

df['Attendance'] = df['Attendance'].apply(attend)

/tmp/ipykernel_4826/3976859995.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Attendance'] = df['Attendance'].apply(attend)

In [ ]:
df

   ID   Name    Math  Science  English  Attendance
0   1  Kunal   77.00     78.0       80        0.92
1   2  Tejas   90.00     88.0       85        0.85
2   3  Rahul   91.75     92.0       70        0.95
3   4  Sujal   66.00     83.0       60        0.40
4   5   Amol  134.00     65.0       75        1.00

In [ ]:
df['Math'] = df['Math'].apply(lambda x: min(x, 100))

/tmp/ipykernel_4826/1324181280.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Math'] = df['Math'].apply(lambda x: min(x, 100))

In [ ]:
df

   ID   Name    Math  Science  English  Attendance
0   1  Kunal   77.00     78.0       80        0.92
1   2  Tejas   90.00     88.0       85        0.85
2   3  Rahul   91.75     92.0       70        0.95
3   4  Sujal   66.00     83.0       60        0.40
4   5   Amol  100.00     65.0       75        1.00

In [ ]:
df['Math'].min()

66.0

In [ ]:

df['Math_log']=np.log(df['Math'])

/tmp/ipykernel_4826/2424573983.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Math_log']=np.log(df['Math'])

In [ ]:

df

   ID   Name    Math  Science  English  Attendance  Math_log
0   1  Kunal   77.00     78.0       80        0.92  4.343805
1   2  Tejas   90.00     88.0       85        0.85  4.499810
2   3  Rahul   91.75     92.0       70        0.95  4.519067
3   4  Sujal   66.00     83.0       60        0.40  4.189655
4   5   Amol  100.00     65.0       75        1.00  4.605170